# The URL the site will be built for
base_url = "https://1zh3n.pages.dev"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "demain"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The site title and description; used in feeds by default.
title = "非真的博客"
description = "非真的博客。Typescript、Rust、Network。"

generate_feed = true


author = "1zh3n（非真）"

[extra]
dark_mode = false

nav = [{ name = "文章", path = "/articles/" }]


icon = "favicon.png"
profile_small = "icon.png"

accent = "#05a081"
accent_light = "#82d0c0"


footer_about = """
Except where otherwise noted , content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/).

Orange favicon by tulpahn - [Flaticon](https://www.flaticon.com/free-icons/orange)
"""

not_found_message = """
This is not the page you're looking for... return back to [home?](/)
"""
