name = "simple dev blog"
description = "A simple dev blog theme"
license = "MIT"
homepage = "https://github.com/bennetthardwick/simple-dev-blog-zola-starter"
min_version = "0.4.0"

[extra]

nav = [
  { name = "About", path = "/about/" },
  { name = "Blog", path = "/blog/" }
]

[author]
name = "Bennett Hardwick"
homepage = "https://bennetthardwick.com"
