name = "my theme name"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/1zh3n/zola-theme"
# The minimum version of Zola required
min_version = "0.1.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "1zh3n"
homepage = "https://1zh3n.dev"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Bennett Hardwick"
homepage = "https://bennett.dev"
repo = "https://github.com/bennetthardwick/simple-dev-blog-zola-starter"
